server:
  port: 8280

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${spring.datasource.hikari.schema}
    hikari:
      username: ${MYSQL_ROOT_USER}
      password: ${MYSQL_ROOT_PASSWORD}
      schema: order_schema
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: ${spring.datasource.hikari.schema}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

client:
  book-service-url: ${BOOK_SERVICE_URL:http://localhost:8080}

springdoc:
  default-produces-media-type: application/json